export interface Word {
    id: string;
    spanish: string;
    english: string;
    category: 'pronoun' | 'grammar' | 'verb' | 'time_place' | 'social' | 'other';
    rank: number; // 1-100
}

export interface Phrase {
    id: string;
    spanish: string;
    english: string;
    wordIds: string[]; // IDs of the core words used in this phrase
}

export const words: Word[] = [
    { id: 'que', spanish: 'que', english: 'that', category: 'grammar', rank: 1 },
    { id: 'de', spanish: 'de', english: 'of/from', category: 'grammar', rank: 2 },
    { id: 'no', spanish: 'no', english: 'no/not', category: 'grammar', rank: 3 },
    { id: 'a', spanish: 'a', english: 'to/at', category: 'grammar', rank: 4 },
    { id: 'la', spanish: 'la', english: 'the (fem)', category: 'grammar', rank: 5 },
    { id: 'el', spanish: 'el', english: 'the (masc)', category: 'grammar', rank: 6 },
    { id: 'es', spanish: 'es', english: 'is', category: 'verb', rank: 7 },
    { id: 'y', spanish: 'y', english: 'and', category: 'grammar', rank: 8 },
    { id: 'en', spanish: 'en', english: 'in/on', category: 'grammar', rank: 9 },
    { id: 'lo', spanish: 'lo', english: 'it', category: 'pronoun', rank: 10 },
    { id: 'un', spanish: 'un', english: 'a/an (masc)', category: 'grammar', rank: 11 },
    { id: 'por', spanish: 'por', english: 'for/by', category: 'grammar', rank: 12 },
    { id: 'que_q', spanish: 'qué', english: 'what/how', category: 'grammar', rank: 13 },
    { id: 'me', spanish: 'me', english: 'me', category: 'pronoun', rank: 14 },
    { id: 'una', spanish: 'una', english: 'a/an (fem)', category: 'grammar', rank: 15 },
    { id: 'te', spanish: 'te', english: 'you', category: 'pronoun', rank: 16 },
    { id: 'los', spanish: 'los', english: 'the (pl)', category: 'grammar', rank: 17 },
    { id: 'se', spanish: 'se', english: 'self', category: 'pronoun', rank: 18 },
    { id: 'con', spanish: 'con', english: 'with', category: 'grammar', rank: 19 },
    { id: 'para', spanish: 'para', english: 'for', category: 'grammar', rank: 20 },
    { id: 'mi', spanish: 'mi', english: 'my', category: 'pronoun', rank: 21 },
    { id: 'esta_v', spanish: 'está', english: 'is', category: 'verb', rank: 22 },
    { id: 'si', spanish: 'si', english: 'if', category: 'grammar', rank: 23 },
    { id: 'bien', spanish: 'bien', english: 'well/good', category: 'social', rank: 24 },
    { id: 'pero', spanish: 'pero', english: 'but', category: 'grammar', rank: 25 },
    { id: 'yo', spanish: 'yo', english: 'I', category: 'pronoun', rank: 26 },
    { id: 'eso', spanish: 'eso', english: 'that', category: 'pronoun', rank: 27 },
    { id: 'las', spanish: 'las', english: 'the (fem pl)', category: 'grammar', rank: 28 },
    { id: 'si_yes', spanish: 'sí', english: 'yes', category: 'social', rank: 29 },
    { id: 'su', spanish: 'su', english: 'his/her/its', category: 'pronoun', rank: 30 },
    { id: 'tu', spanish: 'tu', english: 'your', category: 'pronoun', rank: 31 },
    { id: 'aqui', spanish: 'aquí', english: 'here', category: 'time_place', rank: 32 },
    { id: 'del', spanish: 'del', english: 'of the', category: 'grammar', rank: 33 },
    { id: 'al', spanish: 'al', english: 'to the', category: 'grammar', rank: 34 },
    { id: 'como', spanish: 'como', english: 'like/as', category: 'grammar', rank: 35 },
    { id: 'le', spanish: 'le', english: 'him/her', category: 'pronoun', rank: 36 },
    { id: 'mas', spanish: 'más', english: 'more', category: 'grammar', rank: 37 },
    { id: 'esto', spanish: 'esto', english: 'this', category: 'pronoun', rank: 38 },
    { id: 'ya', spanish: 'ya', english: 'already/now', category: 'time_place', rank: 39 },
    { id: 'todo', spanish: 'todo', english: 'everything', category: 'grammar', rank: 40 },
    { id: 'esta', spanish: 'esta', english: 'this (fem)', category: 'grammar', rank: 41 },
    { id: 'vamos', spanish: 'vamos', english: 'we go/let\'s go', category: 'verb', rank: 42 },
    { id: 'muy', spanish: 'muy', english: 'very', category: 'grammar', rank: 43 },
    { id: 'hay', spanish: 'hay', english: 'there is/are', category: 'verb', rank: 44 },
    { id: 'ahora', spanish: 'ahora', english: 'now', category: 'time_place', rank: 45 },
    { id: 'algo', spanish: 'algo', english: 'something', category: 'grammar', rank: 46 },
    { id: 'estoy', spanish: 'estoy', english: 'I am', category: 'verb', rank: 47 },
    { id: 'tengo', spanish: 'tengo', english: 'I have', category: 'verb', rank: 48 },
    { id: 'nos', spanish: 'nos', english: 'us', category: 'pronoun', rank: 49 },
    { id: 'tu_sub', spanish: 'tú', english: 'you', category: 'pronoun', rank: 50 },
    { id: 'nada', spanish: 'nada', english: 'nothing', category: 'grammar', rank: 51 },
    { id: 'cuando', spanish: 'cuando', english: 'when', category: 'time_place', rank: 52 },
    { id: 'ha', spanish: 'ha', english: 'has', category: 'verb', rank: 53 },
    { id: 'este', spanish: 'este', english: 'this (masc)', category: 'grammar', rank: 54 },
    { id: 'se_know', spanish: 'sé', english: 'I know', category: 'verb', rank: 55 },
    { id: 'estas', spanish: 'estás', english: 'you are', category: 'verb', rank: 56 },
    { id: 'asi', spanish: 'así', english: 'like this', category: 'grammar', rank: 57 },
    { id: 'puedo', spanish: 'puedo', english: 'I can', category: 'verb', rank: 58 },
    { id: 'como_q', spanish: 'cómo', english: 'how', category: 'grammar', rank: 59 },
    { id: 'quiero', spanish: 'quiero', english: 'I want', category: 'verb', rank: 60 },
    { id: 'solo', spanish: 'sólo', english: 'only', category: 'grammar', rank: 61 },
    { id: 'soy', spanish: 'soy', english: 'I am', category: 'verb', rank: 62 },
    { id: 'tiene', spanish: 'tiene', english: 'has', category: 'verb', rank: 63 },
    { id: 'gracias', spanish: 'gracias', english: 'thank you', category: 'social', rank: 64 },
    { id: 'o', spanish: 'o', english: 'or', category: 'grammar', rank: 65 },
    { id: 'el_sub', spanish: 'él', english: 'he', category: 'pronoun', rank: 66 },
    { id: 'bueno', spanish: 'bueno', english: 'good', category: 'social', rank: 67 },
    { id: 'fue', spanish: 'fue', english: 'was/went', category: 'verb', rank: 68 },
    { id: 'ser', spanish: 'ser', english: 'to be', category: 'verb', rank: 69 },
    { id: 'hacer', spanish: 'hacer', english: 'to do/make', category: 'verb', rank: 70 },
    { id: 'son', spanish: 'son', english: 'they are', category: 'verb', rank: 71 },
    { id: 'todos', spanish: 'todos', english: 'everyone', category: 'pronoun', rank: 72 },
    { id: 'era', spanish: 'era', english: 'was', category: 'verb', rank: 73 },
    { id: 'eres', spanish: 'eres', english: 'you are', category: 'verb', rank: 74 },
    { id: 'vez', spanish: 'vez', english: 'time', category: 'time_place', rank: 75 },
    { id: 'tienes', spanish: 'tienes', english: 'you have', category: 'verb', rank: 76 },
    { id: 'creo', spanish: 'creo', english: 'I think', category: 'verb', rank: 77 },
    { id: 'ella', spanish: 'ella', english: 'she', category: 'pronoun', rank: 78 },
    { id: 'he_aux', spanish: 'he', english: 'I have', category: 'verb', rank: 79 },
    { id: 'ese', spanish: 'ese', english: 'that', category: 'grammar', rank: 80 },
    { id: 'voy', spanish: 'voy', english: 'I go', category: 'verb', rank: 81 },
    { id: 'puede', spanish: 'puede', english: 'can', category: 'verb', rank: 82 },
    { id: 'sabes', spanish: 'sabes', english: 'you know', category: 'verb', rank: 83 },
    { id: 'hola', spanish: 'hola', english: 'hello', category: 'social', rank: 84 },
    { id: 'sus', spanish: 'sus', english: 'their', category: 'pronoun', rank: 85 },
    { id: 'porque', spanish: 'porque', english: 'because', category: 'grammar', rank: 86 },
    { id: 'dios', spanish: 'Dios', english: 'God', category: 'social', rank: 87 },
    { id: 'quien', spanish: 'quién', english: 'who', category: 'grammar', rank: 88 },
    { id: 'nunca', spanish: 'nunca', english: 'never', category: 'time_place', rank: 89 },
    { id: 'donde', spanish: 'dónde', english: 'where', category: 'time_place', rank: 90 },
    { id: 'quieres', spanish: 'quieres', english: 'you want', category: 'verb', rank: 91 },
    { id: 'casa', spanish: 'casa', english: 'house', category: 'time_place', rank: 92 },
    { id: 'favor', spanish: 'favor', english: 'favor', category: 'social', rank: 93 },
    { id: 'esa', spanish: 'esa', english: 'that (fem)', category: 'grammar', rank: 94 },
    { id: 'dos', spanish: 'dos', english: 'two', category: 'other', rank: 95 },
    { id: 'tan', spanish: 'tan', english: 'so', category: 'grammar', rank: 96 },
    { id: 'senor', spanish: 'señor', english: 'sir', category: 'social', rank: 97 },
    { id: 'tiempo', spanish: 'tiempo', english: 'time', category: 'time_place', rank: 98 },
    { id: 'verdad', spanish: 'verdad', english: 'truth', category: 'social', rank: 99 },
    { id: 'estaba', spanish: 'estaba', english: 'was', category: 'verb', rank: 100 },
];

export const initialPhrases: Phrase[] = [
    {
        id: 'p1',
        spanish: '¿Qué quieres?',
        english: 'What do you want?',
        wordIds: ['que_q', 'quieres'],
    },
    {
        id: 'p2',
        spanish: 'Es de México.',
        english: 'He/She is from Mexico.',
        wordIds: ['es', 'de'],
    },
    {
        id: 'p3',
        spanish: 'Estoy bien.',
        english: 'I am fine.',
        wordIds: ['estoy', 'bien'],
    },
    {
        id: 'p4',
        spanish: 'Estoy en casa.',
        english: 'I am at home.',
        wordIds: ['estoy', 'en', 'casa'],
    },
    {
        id: 'p5',
        spanish: '¿Dónde estás ahora?',
        english: 'Where are you now?',
        wordIds: ['donde', 'estas', 'ahora'],
    },
    {
        id: 'p6',
        spanish: 'Quiero esto.',
        english: 'I want this.',
        wordIds: ['quiero', 'esto'],
    },
    {
        id: 'p7',
        spanish: 'No sé.',
        english: 'I don\'t know.',
        wordIds: ['no', 'se_know'],
    },
    {
        id: 'p8',
        spanish: 'Hola, ¿cómo estás?',
        english: 'Hello, how are you?',
        wordIds: ['hola', 'como_q', 'estas'],
    },
    {
        id: 'p9',
        spanish: 'Gracias por todo.',
        english: 'Thanks for everything.',
        wordIds: ['gracias', 'por', 'todo'],
    },
    {
        id: 'p10',
        spanish: 'Voy a casa.',
        english: 'I am going home.',
        wordIds: ['voy', 'a', 'casa'],
    },
    {
        id: 'p11',
        spanish: 'Un café, por favor.',
        english: 'A coffee, please.',
        wordIds: ['un', 'por', 'favor'],
    },
    {
        id: 'p12',
        spanish: 'No es para mí.',
        english: 'It is not for me.',
        wordIds: ['no', 'es', 'para', 'mi'],
    },
    {
        id: 'p13',
        spanish: 'Ella está con él.',
        english: 'She is with him.',
        wordIds: ['ella', 'esta_v', 'con', 'el_sub'],
    },
    {
        id: 'p14',
        spanish: '¿Qué es eso?',
        english: 'What is that?',
        wordIds: ['que_q', 'es', 'eso'],
    },
    {
        id: 'p15',
        spanish: 'Todo está bien.',
        english: 'Everything is fine.',
        wordIds: ['todo', 'esta_v', 'bien'],
    },
    {
        id: 'p16',
        spanish: 'Lo quiero ahora.',
        english: 'I want it now.',
        wordIds: ['lo', 'quiero', 'ahora'],
    },
    {
        id: 'p17',
        spanish: 'Sí, es verdad.',
        english: 'Yes, it is true.',
        wordIds: ['si_yes', 'es', 'verdad'],
    },
    {
        id: 'p18',
        spanish: 'No tengo tiempo.',
        english: 'I don\'t have time.',
        wordIds: ['no', 'tengo', 'tiempo'],
    },
    {
        id: 'p19',
        spanish: '¿Dónde está tu casa?',
        english: 'Where is your house?',
        wordIds: ['donde', 'esta_v', 'tu', 'casa'],
    },
    {
        id: 'p20',
        spanish: 'Me gusta mucho.',
        english: 'I like it a lot (It pleases me much).',
        wordIds: ['me', 'mas'], // Approximate mapping for "mucho" using "mas" context or just core words
    },
    {
        id: 'p21',
        spanish: 'Soy de aquí.',
        english: 'I am from here.',
        wordIds: ['soy', 'de', 'aqui'],
    },
    {
        id: 'p22',
        spanish: 'Vamos a ver.',
        english: 'Let\'s see (We go to see).',
        wordIds: ['vamos', 'a'],
    },
    {
        id: 'p23',
        spanish: 'No hay nada aquí.',
        english: 'There is nothing here.',
        wordIds: ['no', 'hay', 'nada', 'aqui'],
    },
    {
        id: 'p24',
        spanish: '¿Quién es ella?',
        english: 'Who is she?',
        wordIds: ['quien', 'es', 'ella'],
    },
    {
        id: 'p25',
        spanish: 'Nunca voy allí.',
        english: 'I never go there.',
        wordIds: ['nunca', 'voy'],
    },
];
